
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Matthias Melcher

/*
 This little toy program displays the content of an Apple Newton MessagePad 
 screen on a modern TFT screen. It does that by grabbing pixel data from
 the internal flat ribbon connector. It then converts the stream of black and
 white pixels into a series of SPI commands and sends them to a screen
 controlled by an ST7769S.

 The current implementation reads the port using one of the CPUs. A future
 version should use DMA and the PIO to read the data and reformat it for 
 easier conversion.

 The SPI output uses the CPU to convert 1bit B&W data into a 16 bit color
 data stream. This need to be made much faster.

 The color information is then copied to the TFT using a bunch of SPI commands.
 Again, this could be done using DMA.

 The LCD port provides only black and white data. The 16 grayscales of the 
 Newton display seem to be generated by changing the output per pixel over 
 time, effectively generating a blinking effect that renders gray thanks to 
 the slow refresh of the 90's LCD technology. To solve this in emulation
 my require averaging pixle brightness over time.

 It would be really nice to support more displays and display types, including 
 e-enk displays. This would require some additional math to keed screen updates
 at a minimum.

 It should be possible to read the touch information from the display SPI and 
 output the analog signal required by the MessagePad.
*/

#include "main.h"
#include "display.h"

#include "pico/stdlib.h"
#include "hardware/gpio.h"

CaptureDevice lcd;
SPI_3Pin spi;


#if defined(DISPLAY_TYPE_GDEH057)
// Hi Res ePaper Display
#elif defined(DISPLAY_TYPE_GDEY058)
// Lo Res ePaper Display
#elif defined(DISPLAY_TYPE_ST7796S)
// Small TFT Display
#else
#error "No display type defined"
#endif


// ----------------------------------------------------------------------------
// Initialize our little LED for control puposes
const uint led_pin = PICO_DEFAULT_LED_PIN;
bool led_state = false;

void led_init() {
    gpio_init(led_pin);
    gpio_set_dir(led_pin, GPIO_OUT);
}

void led_toggle() {
    led_state = ~led_state;
    gpio_put(led_pin, led_state);
}


int main() {
    stdio_init_all();
    led_init();

    EPD_Init(); //Full screen update initialization.
    //EPD_WhiteScreen_White(); //Clear screen function.
    EPD_WhiteScreen_Black(); //Clear screen function.
    EPD_DeepSleep(); //Enter the sleep mode and please do not delete it, otherwise it will reduce the lifespan of the screen.

	sleep_ms(8000); //Delay for 8s.

    EPD_Init(); //Full screen update initialization.
    EPD_WhiteScreen_White(); //Clear screen function.
    EPD_DeepSleep(); //Enter the sleep mode and please do not delete it, otherwise it will reduce the lifespan of the screen.


    //spi.send(0x00, {0x1F, 0x55, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00});
    #if 0      
      delay(2000); //Delay for 2s. 
		 /************Full display(3s)*******************/
			EPD_Init(); //Full screen update initialization.
			EPD_WhiteScreen_ALL(gImage_1); //To Display one image using full screen update.
			EPD_DeepSleep(); //Enter the sleep mode and please do not delete it, otherwise it will reduce the lifespan of the screen.
			delay(2000); //Delay for 2s.
						
			/************Fast update mode(1.5s)*******************/
			EPD_Init_Fast(); //Fast update initialization.
			EPD_WhiteScreen_ALL_Fast(gImage_1); //To display one image using fast update.
			EPD_DeepSleep(); //Enter the sleep mode and please do not delete it, otherwise it will reduce the lifespan of the screen.
			delay(2000); //Delay for 2s.
		
			/************4 Gray update mode(2s)*******************/
			EPD_Init_4G(); //Fast update initialization.
			EPD_WhiteScreen_ALL_4G(gImage_4G1); //To display one image using 4 gray update.
			EPD_DeepSleep(); //Enter the sleep mode and please do not delete it, otherwise it will reduce the lifespan of the screen.
			delay(2000); //Delay for 2s.	

  #if 1 //Partial update demostration.
  //Partial update demo support displaying a clock at 5 locations with 00:00.  If you need to perform partial update more than 5 locations, please use the feature of using partial update at the full screen demo.
  //After 5 partial updatees, implement a full screen update to clear the ghosting caused by partial updatees.
  //////////////////////Partial update time demo/////////////////////////////////////
      EPD_Init(); //Electronic paper initialization.  
      EPD_SetRAMValue_BaseMap(gImage_basemap); //Please do not delete the background color function, otherwise it will cause unstable display during partial update.
      EPD_Init_Part(); //Pa update initialization.
      for(i=0;i<6;i++)
      {
        EPD_Dis_Part_Time(200,180,Num[1],Num[0],gImage_numdot,Num[0],Num[i],5,104,48); //x,y,DATA-A~E,Resolution 48*104                 
      }       
      
      EPD_DeepSleep();  //Enter the sleep mode and please do not delete it, otherwise it will reduce the lifespan of the screen.
      delay(2000); //Delay for 2s.
      EPD_Init(); //Full screen update initialization.
      EPD_WhiteScreen_White(); //Clear screen function.
      EPD_DeepSleep(); //Enter the sleep mode and please do not delete it, otherwise it will reduce the lifespan of the screen.
      delay(2000); //Delay for 2s.
  #endif  
  
  #if 0    //Demo of using partial update to update the full screen, to enable this feature, please change 0 to 1.
  //After 5 partial updatees, implement a full screen update to clear the ghosting caused by partial updatees.
  //////////////////////Partial update time demo/////////////////////////////////////
      EPD_Init(); //Full screen update initialization.
      EPD_WhiteScreen_White(); //Clear screen function.
      EPD_Init_Part();
      EPD_Dis_PartAll(gImage_p1);
      EPD_Dis_PartAll(gImage_p2);

      EPD_DeepSleep();//Enter the sleep mode and please do not delete it, otherwise it will reduce the lifespan of the screen.
      delay(2000); //Delay for 2s. 
      
      EPD_Init(); //Full screen update initialization.
      EPD_WhiteScreen_White(); //Clear screen function.
      EPD_DeepSleep(); //Enter the sleep mode and please do not delete it, otherwise it will reduce the lifespan of the screen.
      delay(2000); //Delay for 2s.
  #endif
  
  #if 0 //Demonstration of full screen update with 180-degree rotation, to enable this feature, please change 0 to 1.
      /************Full display(2s)*******************/
      EPD_Init_180(); //Full screen update initialization.
      EPD_WhiteScreen_ALL(gImage_p1); //To Display one image using full screen update.
      EPD_DeepSleep(); //Enter the sleep mode and please do not delete it, otherwise it will reduce the lifespan of the screen.
      delay(2000); //Delay for 2s.
  #endif        
#endif
}

